// np_fonts.h — declarations for the project's custom LVGL fonts.
// These cover Basic Latin + Latin-1 Supplement + Latin Extended-A + Cyrillic
// so the LCD can render English, Latvian, and Russian without missing-glyph
// rectangles.
//
// The .c source files are generated by tools/build_fonts.sh from Noto Sans.
// They're regenerated automatically by CI before each build.
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(np_font_12);
LV_FONT_DECLARE(np_font_14);
LV_FONT_DECLARE(np_font_16);
LV_FONT_DECLARE(np_font_20);
LV_FONT_DECLARE(np_font_24);
LV_FONT_DECLARE(np_font_28);
LV_FONT_DECLARE(np_font_40);
LV_FONT_DECLARE(np_font_48);

#ifdef __cplusplus
}
#endif
