// relay_icons.h — appliance icons for relay tiles.
//
// We use a small custom LVGL icon font built from a subset of FontAwesome 5
// Free (Solid). Each icon is a Unicode codepoint we render as text.
// Generated by tools/build_icons.sh — see that script for the source font
// and codepoint list.
//
// If the icon font isn't available (e.g. CI hasn't generated it), we fall
// back to short ASCII labels so the build still works.
#pragma once

#include <Arduino.h>
#include <lvgl.h>

// Forward-declared font symbol — defined in src/fonts/np_icons_NN.c when
// generated. The tools/build_fonts.sh CI step produces these.
#ifdef NP_ICONS_AVAILABLE
extern "C" {
LV_FONT_DECLARE(np_icons_24);
LV_FONT_DECLARE(np_icons_40);
}
#define ICON_FONT_24  (&np_icons_24)
#define ICON_FONT_40  (&np_icons_40)
#else
// Fallbacks when the icon font hasn't been generated. The labels render as
// short ASCII abbreviations (PWR, BLB, HTR ...) using the regular text font.
#include "np_fonts.h"
#define ICON_FONT_24  FONT_24
#define ICON_FONT_40  FONT_28
#endif

// Icon ID — stored per relay in NVS, matches the index in g_iconCatalog[].
enum RelayIcon : uint8_t {
    ICON_GENERIC = 0,
    ICON_SOCKET,
    ICON_BULB,
    ICON_HEATER,
    ICON_WATER_HEATER,
    ICON_AC,
    ICON_FAN,
    ICON_FRIDGE,
    ICON_WASHER,
    ICON_DRYER,
    ICON_DISHWASHER,
    ICON_OVEN,
    ICON_MICROWAVE,
    ICON_KETTLE,
    ICON_IRON,
    ICON_CHARGER,
    ICON_PUMP,
    ICON_THERMOSTAT,
    ICON_TV,
    ICON_COMPUTER,
    ICON_LIGHTING,
    ICON_COUNT
};

struct IconCatalogEntry {
    const char* utf8;     // glyph in the icon font (UTF-8)
    const char* fallback; // ASCII fallback if font isn't available
    const char* label;    // human-readable name for the picker UI
    const char* fa;       // FontAwesome 5 Free Solid class name (web UI)
};

// Catalog defined in relay_icons.cpp. Index matches RelayIcon enum.
extern const IconCatalogEntry g_iconCatalog[ICON_COUNT];

// Resolve an icon ID to the right text to display.
// When the icon font is compiled in, returns the Unicode glyph; otherwise
// returns a short ASCII abbreviation.
const char* iconText(RelayIcon i);

// Get the human-readable label for a relay icon (used in the web UI picker).
const char* iconLabel(RelayIcon i);
